plugins {
    id "com.android.application"
}

android {
    namespace "com.qx.strictsignal"
    compileSdk 35

    defaultConfig {
        applicationId "com.qx.strictsignal"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "2.2.0-live-demo-entry"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
